/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email/password login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AuthResponse"];
                        };
                    };
                };
                401: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AuthResponse"];
                        };
                    };
                };
                401: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Venue"][];
                            meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateVenueRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Venue"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Venue"];
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateVenueRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Venue"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["ErrorResponse"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Category"][];
                            meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCategoryRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Category"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Category"];
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCategoryRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Category"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["ErrorResponse"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{venueId}/departments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                };
                header?: never;
                path: {
                    venueId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Department"][];
                            meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDepartmentRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Department"];
                        };
                    };
                };
                409: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{venueId}/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: string;
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Department"];
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDepartmentRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Department"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    venueId: string;
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["ErrorResponse"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"][];
                            meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                    venue?: string;
                    currentVenue?: string;
                    category?: string;
                    department?: string;
                    status?: components["schemas"]["AssetStatus"];
                    responsible?: string;
                    away?: boolean;
                    overdue?: boolean;
                    /** @description free-text on name/serialNumber/assetTag */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Asset"][];
                            meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAssetRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Asset"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Asset"];
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAssetRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Asset"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Movement"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransferAssetRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Asset"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StatusChangeRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Asset"];
                        };
                    };
                };
                409: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignCustodyRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Asset"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/condition": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConditionUpdate"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Asset"];
                        };
                    };
                };
                409: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/qr": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description QR label */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                        "application/pdf": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/qr/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkQrRequest"];
                };
            };
            responses: {
                /** @description combined PDF of labels */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/bulk/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer many assets at once. Validates the whole batch up-front; on any row failure no DB change is made and per-row results are returned. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkTransferRequest"];
                };
            };
            responses: {
                /** @description per-row results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["BulkActionResponse"];
                        };
                    };
                };
                400: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/bulk/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change status on many assets at once. Same all-or-nothing contract as bulk transfer. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkStatusRequest"];
                };
            };
            responses: {
                /** @description per-row results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["BulkActionResponse"];
                        };
                    };
                };
                400: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/condition/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set condition on many assets at once. BEST-EFFORT: each successful item is its own transaction; unaffected items are reported in skipped[] with a reason (not_found, forbidden, unchanged). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkConditionUpdate"];
                };
            };
            responses: {
                /** @description bulk summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["BulkConditionResult"];
                        };
                    };
                };
                400: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan/{qrToken}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qrToken: components["parameters"]["QrTokenPath"];
            };
            cookie?: never;
        };
        /** PUBLIC — resolve a scanned QR code. Custodian contact details masked. Resolves for lost/retired. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    qrToken: components["parameters"]["QrTokenPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["PublicAssetView"];
                        };
                    };
                };
                404: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                    status?: components["schemas"]["PurchaseOrderStatus"];
                    responsible?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["PurchaseOrder"][];
                            meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePurchaseOrderRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["PurchaseOrder"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["PurchaseOrder"];
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePurchaseOrderRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["PurchaseOrder"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-orders/{id}/receive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generates one asset per unit per line item in a single Mongo transaction. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReceivePurchaseOrderRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ReceivePurchaseOrderResponse"];
                        };
                    };
                };
                409: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/purchase-orders/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the CSV import template. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV template */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/purchase-orders/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dry-run a CSV/XLSX upload. Writes ImportJob with status=preview_ready. Creates no POs or assets. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        /** @description JSON-encoded ImportJobOptions. */
                        options?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ImportPreview"];
                        };
                    };
                };
                400: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/purchase-orders/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit a previously-validated import. Creates POs + assets (one Mongo tx per PO). Notifications suppressed. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommitImportRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ImportJob"];
                        };
                    };
                };
                409: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ImportJob"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Downloadable CSV report of created POs + assets (with tags) and skipped/errored rows. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description result csv */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                    status?: components["schemas"]["RepairStatus"];
                    assetId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Repair"][];
                            meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRepairRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Repair"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repairs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Repair"];
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRepairRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Repair"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["DashboardSummary"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/inventory-by-venue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["InventoryByVenueRow"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/assets-away": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Asset"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/assets-overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Asset"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/in-repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Repair"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/by-responsible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["AssetsByResponsibleRow"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/by-department": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Optional venue scope; when omitted, admins get all venues. */
                    venue?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["DepartmentAssetCountRow"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the caller's password. Requires the current password. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description password changed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ErrorResponse"];
                401: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notification-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                notifyByEmail?: boolean;
                            };
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateNotificationPreferencesRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                notifyByEmail?: boolean;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Outbox log (admin) */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                    status?: components["schemas"]["NotificationStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Notification"][];
                            meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ObjectId: string;
        Pagination: {
            page: number;
            limit: number;
            /** Format: int64 */
            total: number;
            totalPages: number;
        };
        Meta: {
            pagination?: components["schemas"]["Pagination"];
        };
        ErrorPayload: {
            /** @enum {string} */
            kind: "bad_request" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "validation" | "internal" | "http_error";
            message: string;
            fields?: {
                [key: string]: string;
            };
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorPayload"];
        };
        /** @enum {string} */
        Role: "admin" | "venue_manager" | "staff";
        /** @enum {string} */
        AssetStatus: "available" | "in_use" | "in_repair" | "retired" | "lost";
        /** @enum {string} */
        AssetCondition: "new" | "good" | "fair" | "poor";
        /** @enum {string} */
        MovementType: "transfer" | "status_change" | "custody_change" | "condition_change" | "repair_in" | "repair_out";
        /** @enum {string} */
        RepairStatus: "open" | "in_progress" | "completed" | "unrepairable";
        /** @enum {string} */
        PurchaseOrderStatus: "draft" | "ordered" | "received" | "cancelled";
        /** @enum {string} */
        NotificationType: "overdue" | "custody_change" | "transfer" | "repair_update";
        /** @enum {string} */
        NotificationStatus: "queued" | "sent" | "failed";
        /** @enum {string} */
        NotificationChannel: "email";
        /** @enum {string} */
        CustomFieldType: "string" | "number" | "boolean" | "date";
        User: {
            id: components["schemas"]["ObjectId"];
            name: string;
            /** Format: email */
            email: string;
            passwordHash: string;
            role: components["schemas"]["Role"];
            /** @description Job title, e.g. "IT Staff", "Event Manager" */
            position: string;
            venueIds: components["schemas"]["ObjectId"][];
            notifyByEmail: boolean;
            phone?: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description User identity safe to expose on the public scan view (no email/phone). */
        PublicUserContact: {
            id: components["schemas"]["ObjectId"];
            name: string;
            role: components["schemas"]["Role"];
            position: string;
        };
        Venue: {
            id: components["schemas"]["ObjectId"];
            name: string;
            code: string;
            address?: string;
            city?: string;
            type: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CategoryCustomField: {
            key: string;
            label: string;
            type: components["schemas"]["CustomFieldType"];
            required: boolean;
        };
        Category: {
            id: components["schemas"]["ObjectId"];
            name: string;
            slug: string;
            description?: string;
            customFields: components["schemas"]["CategoryCustomField"][];
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Department: {
            id: components["schemas"]["ObjectId"];
            venueId: components["schemas"]["ObjectId"];
            name: string;
            code: string;
            description?: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Asset: {
            id: components["schemas"]["ObjectId"];
            assetTag: string;
            qrToken: string;
            name: string;
            categoryId: components["schemas"]["ObjectId"];
            homeVenueId: components["schemas"]["ObjectId"];
            currentVenueId: components["schemas"]["ObjectId"];
            departmentId?: components["schemas"]["ObjectId"];
            status: components["schemas"]["AssetStatus"];
            condition: components["schemas"]["AssetCondition"];
            responsibleUserId?: components["schemas"]["ObjectId"];
            purchaseOrderId?: components["schemas"]["ObjectId"];
            /** Format: date-time */
            purchaseDate?: string;
            serialNumber?: string;
            /** @description Free-form map of category-defined custom fields. */
            specs?: {
                [key: string]: unknown;
            };
            photos?: string[];
            /** Format: date-time */
            expectedReturnDate?: string;
            isOverdue: boolean;
            notes?: string;
            isActive: boolean;
            importJobId?: components["schemas"]["ObjectId"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PublicAssetView: {
            asset: components["schemas"]["Asset"];
            responsiblePerson?: components["schemas"]["PublicUserContact"];
            homeVenueName?: string;
            currentVenueName?: string;
            categoryName?: string;
            departmentName?: string;
        };
        PurchaseOrderSupplier: {
            name: string;
            contact?: string;
        };
        PurchaseOrderLineItem: {
            categoryId: components["schemas"]["ObjectId"];
            name: string;
            quantity: number;
        };
        PurchaseOrder: {
            id: components["schemas"]["ObjectId"];
            poNumber: string;
            supplier: components["schemas"]["PurchaseOrderSupplier"];
            responsibleUserId: components["schemas"]["ObjectId"];
            /** Format: date-time */
            orderDate: string;
            /** Format: date-time */
            receivedDate?: string;
            status: components["schemas"]["PurchaseOrderStatus"];
            lineItems: components["schemas"]["PurchaseOrderLineItem"][];
            attachments?: string[];
            notes?: string;
            createdBy: components["schemas"]["ObjectId"];
            importJobId?: components["schemas"]["ObjectId"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Movement: {
            id: components["schemas"]["ObjectId"];
            assetId: components["schemas"]["ObjectId"];
            type: components["schemas"]["MovementType"];
            fromVenueId?: components["schemas"]["ObjectId"];
            toVenueId?: components["schemas"]["ObjectId"];
            fromStatus?: components["schemas"]["AssetStatus"];
            toStatus?: components["schemas"]["AssetStatus"];
            fromCondition?: components["schemas"]["AssetCondition"];
            toCondition?: components["schemas"]["AssetCondition"];
            fromUserId?: components["schemas"]["ObjectId"];
            toUserId?: components["schemas"]["ObjectId"];
            reason?: string;
            notes?: string;
            /** Format: date-time */
            expectedReturnDate?: string;
            performedBy: components["schemas"]["ObjectId"];
            /** Format: date-time */
            performedAt: string;
        };
        Repair: {
            id: components["schemas"]["ObjectId"];
            assetId: components["schemas"]["ObjectId"];
            issue: string;
            reportedBy: components["schemas"]["ObjectId"];
            /** Format: date-time */
            reportedAt: string;
            status: components["schemas"]["RepairStatus"];
            vendor?: string;
            /** Format: date-time */
            sentAt?: string;
            /** Format: date-time */
            returnedAt?: string;
            resolution?: string;
            notes?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Notification: {
            id: components["schemas"]["ObjectId"];
            type: components["schemas"]["NotificationType"];
            recipientUserId: components["schemas"]["ObjectId"];
            /**
             * Format: email
             * @description Snapshotted at enqueue time so worker sends do not need a DB lookup.
             */
            recipientEmail: string;
            subject: string;
            body: string;
            assetId?: components["schemas"]["ObjectId"];
            channel: components["schemas"]["NotificationChannel"];
            status: components["schemas"]["NotificationStatus"];
            attempts: number;
            /** Format: date-time */
            sentAt?: string;
            error?: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuditLog: {
            id: components["schemas"]["ObjectId"];
            entityType: string;
            entityId: components["schemas"]["ObjectId"];
            action: string;
            changes?: {
                [key: string]: unknown;
            };
            performedBy: components["schemas"]["ObjectId"];
            /** Format: date-time */
            performedAt: string;
            ip?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        TokenPair: {
            accessToken: string;
            refreshToken: string;
            /**
             * Format: int64
             * @description unix seconds
             */
            accessExp: number;
            /**
             * Format: int64
             * @description unix seconds
             */
            refreshExp: number;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            tokens: components["schemas"]["TokenPair"];
        };
        CreateVenueRequest: {
            name: string;
            code: string;
            address?: string;
            city?: string;
            type: string;
            /** @default true */
            isActive: boolean;
        };
        UpdateVenueRequest: {
            name?: string;
            code?: string;
            address?: string;
            city?: string;
            type?: string;
            isActive?: boolean;
        };
        CreateCategoryRequest: {
            name: string;
            slug: string;
            description?: string;
            customFields?: components["schemas"]["CategoryCustomField"][];
            /** @default true */
            isActive: boolean;
        };
        UpdateCategoryRequest: {
            name?: string;
            slug?: string;
            description?: string;
            customFields?: components["schemas"]["CategoryCustomField"][];
            isActive?: boolean;
        };
        CreateDepartmentRequest: {
            name: string;
            code: string;
            description?: string;
            /** @default true */
            isActive: boolean;
        };
        UpdateDepartmentRequest: {
            name?: string;
            code?: string;
            description?: string;
            isActive?: boolean;
        };
        CreateUserRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            role: components["schemas"]["Role"];
            position: string;
            venueIds?: components["schemas"]["ObjectId"][];
            /** @default true */
            notifyByEmail: boolean;
            phone?: string;
        };
        UpdateUserRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            password?: string;
            role?: components["schemas"]["Role"];
            position?: string;
            venueIds?: components["schemas"]["ObjectId"][];
            notifyByEmail?: boolean;
            phone?: string;
            isActive?: boolean;
        };
        UpdateNotificationPreferencesRequest: {
            notifyByEmail: boolean;
        };
        ChangePasswordRequest: {
            /** @description The caller's current password, used to re-authenticate the change. */
            current: string;
            /** @description The new password. 8-72 characters (bcrypt's 72-byte ceiling). */
            next: string;
        };
        CreateAssetRequest: {
            name: string;
            categoryId: components["schemas"]["ObjectId"];
            homeVenueId: components["schemas"]["ObjectId"];
            currentVenueId?: components["schemas"]["ObjectId"];
            departmentId?: components["schemas"]["ObjectId"];
            condition: components["schemas"]["AssetCondition"];
            responsibleUserId?: components["schemas"]["ObjectId"];
            purchaseOrderId?: components["schemas"]["ObjectId"];
            /** Format: date-time */
            purchaseDate?: string;
            serialNumber?: string;
            specs?: {
                [key: string]: unknown;
            };
            photos?: string[];
            notes?: string;
        };
        UpdateAssetRequest: {
            name?: string;
            categoryId?: components["schemas"]["ObjectId"];
            homeVenueId?: components["schemas"]["ObjectId"];
            departmentId?: components["schemas"]["ObjectId"];
            condition?: components["schemas"]["AssetCondition"];
            serialNumber?: string;
            specs?: {
                [key: string]: unknown;
            };
            photos?: string[];
            notes?: string;
            isActive?: boolean;
        };
        TransferAssetRequest: {
            toVenueId: components["schemas"]["ObjectId"];
            /**
             * Format: date-time
             * @description If set, the asset is a temporary transfer subject to overdue checks.
             */
            expectedReturnDate?: string;
            notes?: string;
        };
        StatusChangeRequest: {
            status: components["schemas"]["AssetStatus"];
            reason?: string;
        };
        ConditionUpdate: {
            condition: components["schemas"]["AssetCondition"];
            notes?: string;
        };
        AssignCustodyRequest: {
            responsibleUserId: components["schemas"]["ObjectId"];
            notes?: string;
        };
        BulkQrRequest: {
            assetIds: components["schemas"]["ObjectId"][];
        };
        BulkTransferRequest: {
            assetIds: components["schemas"]["ObjectId"][];
            toVenueId: components["schemas"]["ObjectId"];
            /**
             * Format: date-time
             * @description Applied to every asset in the batch that is NOT returning to its home venue.
             */
            expectedReturnDate?: string;
            notes?: string;
        };
        BulkStatusRequest: {
            assetIds: components["schemas"]["ObjectId"][];
            status: components["schemas"]["AssetStatus"];
            reason?: string;
        };
        BulkActionResult: {
            assetId: components["schemas"]["ObjectId"];
            ok: boolean;
            /** @description Present iff ok=false. Per-row reason: not_found, forbidden, invalid_transition, dest_venue_forbidden, etc. */
            error?: string;
        };
        BulkActionResponse: {
            total: number;
            succeeded: number;
            failed: number;
            results: components["schemas"]["BulkActionResult"][];
        };
        BulkConditionUpdate: {
            assetIds: components["schemas"]["ObjectId"][];
            condition: components["schemas"]["AssetCondition"];
            notes?: string;
        };
        BulkConditionSkipped: {
            id: components["schemas"]["ObjectId"];
            /** @description One of: not_found, forbidden, unchanged. */
            reason: string;
        };
        BulkConditionResult: {
            updated: number;
            skipped: components["schemas"]["BulkConditionSkipped"][];
        };
        CreatePurchaseOrderRequest: {
            poNumber: string;
            supplier: components["schemas"]["PurchaseOrderSupplier"];
            responsibleUserId: components["schemas"]["ObjectId"];
            /** Format: date-time */
            orderDate: string;
            lineItems: components["schemas"]["PurchaseOrderLineItem"][];
            attachments?: string[];
            notes?: string;
        };
        UpdatePurchaseOrderRequest: {
            poNumber?: string;
            supplier?: components["schemas"]["PurchaseOrderSupplier"];
            responsibleUserId?: components["schemas"]["ObjectId"];
            /** Format: date-time */
            orderDate?: string;
            lineItems?: components["schemas"]["PurchaseOrderLineItem"][];
            attachments?: string[];
            notes?: string;
            status?: components["schemas"]["PurchaseOrderStatus"];
        };
        ReceivePurchaseOrderRequest: {
            /** @description Home venue for every asset generated by this receive. */
            venueId: components["schemas"]["ObjectId"];
            /** @description Optional home department for every asset generated by this receive. Must belong to venueId. */
            departmentId?: components["schemas"]["ObjectId"];
        };
        ReceivePurchaseOrderResponse: {
            purchaseOrder: components["schemas"]["PurchaseOrder"];
            generatedAssetIds: components["schemas"]["ObjectId"][];
        };
        CreateRepairRequest: {
            assetId: components["schemas"]["ObjectId"];
            issue: string;
            vendor?: string;
            notes?: string;
        };
        UpdateRepairRequest: {
            status?: components["schemas"]["RepairStatus"];
            vendor?: string;
            /** Format: date-time */
            sentAt?: string;
            /** Format: date-time */
            returnedAt?: string;
            resolution?: string;
            notes?: string;
        };
        DashboardVenueCount: {
            venueId: components["schemas"]["ObjectId"];
            venueName: string;
            count: number;
        };
        DashboardSummary: {
            totalAssets: number;
            byStatus: {
                [key: string]: number;
            };
            byVenue: components["schemas"]["DashboardVenueCount"][];
            awayFromHome: number;
            inRepair: number;
            overdue: number;
        };
        InventoryByVenueRow: {
            venueId: components["schemas"]["ObjectId"];
            venueName: string;
            total: number;
            byStatus?: {
                [key: string]: number;
            };
            byDepartment?: components["schemas"]["DepartmentAssetCountRow"][];
        };
        DepartmentAssetCountRow: {
            departmentId: components["schemas"]["ObjectId"];
            departmentName: string;
            count: number;
        };
        AssetsByResponsibleRow: {
            userId: components["schemas"]["ObjectId"];
            userName: string;
            position?: string;
            count: number;
        };
        /** @enum {string} */
        ImportJobStatus: "validating" | "preview_ready" | "importing" | "completed" | "failed" | "rolled_back";
        /** @enum {string} */
        ImportConflictPolicy: "error" | "skipExisting";
        ImportJobOptions: {
            /** @description Behaviour when a poNumber already exists. Default: error. */
            onConflict?: components["schemas"]["ImportConflictPolicy"];
            /** @description If true, commit valid rows and skip errored ones rather than rejecting the whole job. */
            importValidOnly?: boolean;
        };
        ImportJobCounts: {
            posTotal: number;
            posCreated: number;
            assetsCreated: number;
            rowsSkipped: number;
            rowsErrored: number;
        };
        ImportRowError: {
            /** @description 1-based row in the uploaded file (header = 1, first data row = 2). */
            row: number;
            field?: string;
            message: string;
        };
        ImportJob: {
            id: components["schemas"]["ObjectId"];
            filename: string;
            uploadedBy: components["schemas"]["ObjectId"];
            status: components["schemas"]["ImportJobStatus"];
            options: components["schemas"]["ImportJobOptions"];
            counts: components["schemas"]["ImportJobCounts"];
            errors: components["schemas"]["ImportRowError"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        ImportPreviewPO: {
            poNumber: string;
            lineItems: number;
            assetCount: number;
            categories?: string[];
            venues?: string[];
            skipExisting?: boolean;
        };
        ImportPreview: {
            job: components["schemas"]["ImportJob"];
            posPreview: components["schemas"]["ImportPreviewPO"][];
        };
        CommitImportRequest: {
            importJobId: components["schemas"]["ObjectId"];
            options?: components["schemas"]["ImportJobOptions"];
        };
    };
    responses: {
        /** @description Error envelope */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        PageParam: number;
        LimitParam: number;
        IdPath: string;
        QrTokenPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
